---
include:

    # nice
  - board: nice_nano_v2
    artifact-name: nice_corne_left
    shield: corne_left # for OLED no nice_view
  - board: nice_nano_v2
    artifact-name: nice_corne_right
    shield: corne_right # # for OLED no nice_view

    # peripheral_left
  - board: nice_nano_v2
    shield: corne_left_peripheral
    artifact-name: nice_corne_left_peripheral

    # ProMicro_Dongle
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne Dongle\"
    artifact-name: nice_corne_dongle_pro_micro
    snippet: zmk-usb-logging

    # settings_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
